### PR TITLE
Addqscan

### PR DESCRIPTION
**Pull request by tdent**

### CODE REVIEW

**Comment by tdent** [comment]
@spxiwh any review?

**Review by spxiwh — APPROVED** [review]

**Comment by spxiwh** [comment]
Certainly the patch does what it says, so I'm approving, but I'm still unsure as to how we decide what ini files to update as code changes and when we just say that this config needs to run with an older code version.

**Comment by tdent** [comment]
You and everyone else @spxiwh , given that our leader doesn't seem to care either way.  I don't think this is the right venue for debating it again.

**Comment by spxiwh** [comment]
Yep ... As I said, the patch is approved.

**Comment by stevereyes01** [comment]
Just so you know, the current defaults of the workflow make these sections required (I tried running without them and my workflows got upset). So somebody should really merge them if anyone wants to run a search workflow.

**Pull request merged**
