### PR TITLE
Update tag names

### PR DESCRIPTION
**Pull request by spxiwh**
This pull request is required to merge:

https://github.com/gwastro/pycbc/pull/2422

as it updates the config files' tag names.

### CODE REVIEW

**Comment by ahnitz** [comment]
@spxiwh @duncan-brown I'm starting to think we should have a separate set of config files for testing. It seems odd to be updating the config files in the O2 folder. Also, I don't think we should be pointing the pycbc repo to a specific tag of this one, it should point to master and we should make sure that master of pycbc alwasy works with some set of config files of master here. 

Thoughts?

**Comment by duncan-brown** [comment]
There are pluses and minuses to the way we do it at the moment. It’s good to make sure that the last production analysis we did works, but we should also have some way of testing master. 

I won’t have chance to look at this until GWPAW. Can we figure out what to do then?

**Comment by tdent** [comment]
Status update on this please?

**Comment by spxiwh** [comment]
This was resolved by making this change in the new workflow, but not in the old one. The config files for the new workflow are already updated. Closing this.

**Pull request closed without merging**
