### PR TITLE
Add a section to set number of hierarchical removals

### PR DESCRIPTION
**Pull request by duncan-brown**
The user should set ``max-hierarchical-removal`` in the ``[workflow-results]`` section and then this is propagated to statmap. The values is used in ``pycbc_make_coinc_search_workflow`` to generate ``max-hierarchical-removal`` invocations of the various plotting codes.

### CODE REVIEW

**Comment by tdent** [comment]
any particular reason for 5 by the way?

**Comment by duncan-brown** [comment]
@tdent not really. Larger than 1 and smaller than 10?

**Comment by tdent** [comment]
Wasn't there once an option to do the removal repeatedly until there were no 'zero-far' things left to remove ?

**Comment by duncan-brown** [comment]
@tdent there was, but @cdcapano did not like it for some reason.

**Comment by tdent** [comment]
5 ought to be OK until .. the 2nd week of O3, I guess.

**Comment by stevereyes01** [comment]
Do we want to try this with a `--config-override` before we merge this?

**Review by stevereyes01 — APPROVED** [review]
This will hopefully work when the rest of the code has been merged. We should wait until then before merging this.

**Pull request merged**
